### PR TITLE
Test for fetchLinkMedia

### PR DESCRIPTION
**Pull request by tzafrir**

### CODE REVIEW

**Comment by mohamedmansour** [comment]
Great, just a quick question, is it better to let fetchLinkMedia have a structured response instead of a array response or that response helps us when we consume that?

**Comment by tzafrir** [comment]
I made it that way so I can test for response.error, don't mind it being done any other way.

**Comment by mohamedmansour** [comment]
I would rather like the API to return a structured JSON object with human readable keys so it is easier to understand, than an array of arrays. Dunno :)

**Comment by tzafrir** [comment]
It does: response is an object with either .error or .items. The .items member is indeed an array of arrays - each of those arrays is a media object (which is the same as the output of _createMediaBase). Creating a post based on a URL looks like this:

`plus.fetchLinkMedia(function(response) {
  if (!response.error && response.items.length > 0) {
    var post = {'rawMedia': response.items};
    plus.newPost(callback, post);
  }
}, 'http://anyurl.com');`

**Pull request merged**
