### PR TITLE
Adding multimedia support for new posts

### PR DESCRIPTION
**Pull request by quietlynn**
Supports links and images. No video support yet.

Maybe I can add a link preview API for generating media items automatically.

https://plus.google.com/_/sharebox/linkpreview/

### CODE REVIEW

**Comment by mohamedmansour** [comment]
I merged 73869c166313e793233371b4abee11fcf65c63b9 and 11118c0bfc7b67bbeb74d2e7afba595ddc7ca692 :)

**Comment by mohamedmansour** [comment]
Hey @quietlynn  can you update your fork, your tree is a bit behind and would make it easier for me to merge :)

**Comment by mohamedmansour** [comment]
And I removed all the parameters to be an object, because we would need to support more parameters in the future, easier to maintain this way :)

**Comment by quietlynn** [comment]
Okay, I'll update my fork when I am able to use my PC. :)

**Pull request closed without merging**
